# Site settings
title: "Lanka Data Foundation"
description: "Empowering communities"
url: "https://your-domain.com"
baseurl: ""

# Contact information
email: ""
phone: "+1 (555) 123-4567"
address: "123 Transparency Ave, Open City"

# Social media
social:
  facebook: "https://facebook.com/dataforall"
  twitter: "https://twitter.com/dataforall"
  instagram: "https://instagram.com/dataforall"
  linkedin: "https://linkedin.com/company/dataforall"

# Statistics
stats:
  datasets: "50K+"
  users: "100K+"
  cities: "25+"
  subscribers: "10,000+"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  datasets:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
