# Site settings
title: "Open Data"
description: "Empowering communities with public"
url: "https://your-domain.com"
baseurl: ""

# Contact information
email: "contact@datafoundation.lk"
phone: "+94 77 386 7813"
address: "No. 248/201 Hill street Dehiwala, Sri Lanka"

# Social media
social:
  linkedin: "https://www.linkedin.com/company/lankadata/"

# Statistics
stats:
  datasets: "50K+"
  users: "100K+"
  cities: "25+"
  subscribers: "10,000+"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  datasets:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
